version: '3.1'
services:
  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command:
      [
        '--max_allowed_packet=1GB',
        '--default-authentication-plugin=mysql_native_password'
      ]
    environment:
      MYSQL_DATABASE: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
  admin:
    network_mode: host
    image: adminer
    restart: always
    depends_on:
      - postgres
      - mysql
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_PLUGINS: 'tables-filter tinymce json-column struct-comments table-structure table-indexes-structure frames'
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-local'
    ports:
        - 4369:4369
        - 5671:5671
        - 5672:5672
        - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ./data/rabbitmq/lib:/var/lib/rabbitmq

volumes:
  mysql:
    driver: local
  postgres:
    driver: local

  rabbitmq:
    driver: local
